apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: {{ include "springboot-tekton.fullname" . }}-tt
spec:
  params:
  - name: git-repo-url
    description: The git repository url
  - name: git-commit-id
    description: The git commit sha
  - name: git-branch
    description: The git revision
    default: master
  - name: git-repo-name
    description: The name of the deployment to be created / patched
####
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: $(params.git-repo-name)-code-$(uid)
      labels:
        commit-id: $(params.git-commit-id)
        # branch: $(params.git-branch)
    spec:
      type: git
      params:
      - name: url
        value: $(params.git-repo-url)
      - name: revision
        value: $(params.git-branch)
  ####
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: $(params.git-repo-name)-man-$(uid)
      labels:
        commit-id: $(params.git-commit-id)
        # branch: $(params.git-branch)
    spec:
      type: git
      params:
      - name: url
        value: $(params.git-repo-url)
      - name: revision
        value: $(params.git-branch)
  ####
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: $(params.git-repo-name)-pr-$(uid)
      labels:
        commit-id: $(params.git-commit-id)
    spec:
      pipelineRef:
        name: {{ include "springboot-tekton.fullname" . }}-pipeline
      resources:
      - name: {{ include "springboot-tekton.fullname" . }}-git
        resourceRef:
          name: $(params.git-repo-name)-code-$(uid)
      - name: {{ include "springboot-tekton.fullname" . }}-templates
        resourceRef:
          name: $(params.git-repo-name)-man-$(uid)
      - name: {{ include "springboot-tekton.fullname" . }}-image
        resourceRef:
          name: {{ include "springboot-tekton.fullname" . }}-image
      serviceAccountName: {{ .Values.serviceAccount.name }}
      workspaces:
      - name: local-maven-repo
        persistentVolumeClaim:
          claimName: maven-repo-pvc-spring-rest
      timeout: 1h0m0s


